// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-DLxDDzuIYE6IMmdwLxnJbVWn767a3Xg',
    appId: '1:138946335477:web:6121eef95bcabf57ab6bbc',
    messagingSenderId: '138946335477',
    projectId: 'authentiction-task',
    authDomain: 'authentiction-task.firebaseapp.com',
    databaseURL: 'https://authentiction-task-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'authentiction-task.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbuk54LMOHwRILLHf94xZttNNbvBLmDVU',
    appId: '1:138946335477:android:307e958e2dccf67eab6bbc',
    messagingSenderId: '138946335477',
    projectId: 'authentiction-task',
    databaseURL: 'https://authentiction-task-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'authentiction-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCks1WDjeQ511VM6pVseiJtZnQn-NN9nuM',
    appId: '1:138946335477:ios:d7e88c4c334bd82eab6bbc',
    messagingSenderId: '138946335477',
    projectId: 'authentiction-task',
    databaseURL: 'https://authentiction-task-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'authentiction-task.firebasestorage.app',
    iosBundleId: 'com.example.iotControlApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCks1WDjeQ511VM6pVseiJtZnQn-NN9nuM',
    appId: '1:138946335477:ios:d7e88c4c334bd82eab6bbc',
    messagingSenderId: '138946335477',
    projectId: 'authentiction-task',
    databaseURL: 'https://authentiction-task-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'authentiction-task.firebasestorage.app',
    iosBundleId: 'com.example.iotControlApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-DLxDDzuIYE6IMmdwLxnJbVWn767a3Xg',
    appId: '1:138946335477:web:446687f1ab7e3296ab6bbc',
    messagingSenderId: '138946335477',
    projectId: 'authentiction-task',
    authDomain: 'authentiction-task.firebaseapp.com',
    databaseURL: 'https://authentiction-task-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'authentiction-task.firebasestorage.app',
  );
}
